highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true
url: https://jfernancordova.github.io
baseurl: /
title: José Córdova
author: José Córdova
description: Personal blog and resume
avatar: profile.png
email: jfernancordova@gmail.com
github: jfernancordova
linkedin: jfernancordova
twitter: jfernancordova
disqus: jfernancordova
google_analytics: UA-69391421-1
